### ISSUE TITLE
oauth redirection callback

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#1120]
the redirection goes to `https://api.alpha.caliopen.org/api/v2/providers/.../callback...` instead of `https://alpha.caliopen.org/api/v2/providers/.../callback...` 
has described in the provider request:

```
// GET https://alpha.caliopen.org/api/v2/providers/gmail
{"name":"gmail","oauth_callback_uri":"/api/v2/providers/gmail/callback","oauth_request_url":"..."}
```

So the popup cannot be closed automatically

**Comment by sapiens-sapide** [comment]
@iamdey : on `GET https://alpha.caliopen.org/api/v2/providers/gmail` you get back a _relative_ uri, not a complete URL.  
popup should check only if _URI_ has been called, shouldn't it ?

**Comment by iamdey** [comment]
popup detector should check when browser is back on the instance domain.

the relative URI should work with relative URI:
`popup.window.location.href.includes(popup.provider.oauth_callback_uri)`

But it fails and I suppose it is due to CORS that avoid access to the content of the window, since the actual URI is `https://api.alpha.caliopen.org...`

Afterward I think there is an other pbm with this URI : caliopen bearer is managed by express and (for now) nobody should access to `https://api.xxxx` directly.

Finally, the solution should be to redirect the browser to `https://mon.instance-caliopen.tld/...`, in our case: `https://alpha.caliopen.org/api/v2/...`

**Comment by gdchamal** [comment]
I agree with @iamdey , the callback MUST be on a client URL not api one (even if it works)

**Comment by sapiens-sapide** [comment]
Just do it ! It is client's role to make the callback and both api.alpha… and alpha… are registred in google and twitter consoles.

**Comment by sapiens-sapide** [comment]
proposal to modify apiv2.yaml config file to explicitely name the callback base url : 
- remove `hostname` and `port` at top of file
- modify `Providers` section for this : 
```yaml
  Providers:                                                # temporary supported providers list for remote identities before moving this data into store facility
    callback_base_url: http://localhost:6544
    providers:
    - name: gmail
      protocol: email
      infos:
        client_id:
        client_secret:
        imapserver: imap.gmail.com:993
        smtpserver: smtp.gmail.com:587
    - name: twitter
      protocol: twitter
      infos:
        consumer_key: 
        consumer_secret:
```
