### ISSUE TITLE
unable to save a new draft

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#276]
> Request URL:http://localhost:4000/api/v1/messages
> Request Method:POST
> Status Code:422 Unprocessable Entity
> Request Payload

```
{
	"discussion_id": "392c708b-79bf-4559-a4f7-f3b251aa7125",
	"body": "foo",
	"identities": [{
		"display_name": "None None",
		"identifier": "dev@caliopen.local",
		"status": "active",
		"type": "email",
		"user_id": "ae5c0c9d-163a-4600-be10-751e9e2bcb23"
	}]
}
```

> Response

```
errors:
  0:
    code: 422
    component: : "collection_message"
    description: "Application encountered an error when applying patch"
    message: "list of participants is not consistent for this discussion"
    property: "MergePatchError"
    type: "Patch Error"
    values: 422
```
---

I tried to POST with or without participants and get same error: 

```
{
	"discussion_id": "392c708b-79bf-4559-a4f7-f3b251aa7125",
	"body": "foo",
	"identities": [{
		"display_name": "None None",
		"identifier": "dev@caliopen.local",
		"status": "active",
		"type": "email",
		"user_id": "ae5c0c9d-163a-4600-be10-751e9e2bcb23"
	}],
        "participants: []
}
```

I remember we talk about this and I should not send any participants, or we changed back to first idea that I extract it from the discussion ?
